export const GET_BOMS_RESPONSE = "GET_BOMS_RESPONSE";
export const GET_BOM_RESPONSE = "GET_BOM_RESPONSE";
export const ADD_NEW_BOM_RESPONSE = "ADD_NEW_BOM_RESPONSE";
export const UPDATE_EXISTING_BOM_RESPONSE = "UPDATE_EXISTING_BOM_RESPONSE";
export const DELETE_BOM_RESPONSE = "DELETE_BOM_RESPONSE";

export const GET_BOMLINES_RESPONSE = "GET_BOMLINES_RESPONSE";
export const GET_BOMLINE_RESPONSE = "GET_BOMLINE_RESPONSE";
export const ADD_NEW_BOMLINE_RESPONSE = "ADD_NEW_BOMLINE_RESPONSE";
export const UPDATE_EXISTING_BOMLINE_RESPONSE =
  "UPDATE_EXISTING_BOMLINE_RESPONSE";
export const DELETE_BOMLINE_RESPONSE = "DELETE_BOMLINE_RESPONSE";

export const GET_DELIVERS_RESPONSE = "GET_DELIVERS_RESPONSE";
export const GET_DELIVER_RESPONSE = "GET_DELIVER_RESPONSE";
export const ADD_NEW_DELIVER_RESPONSE = "ADD_NEW_DELIVER_RESPONSE";
export const UPDATE_EXISTING_DELIVER_RESPONSE =
  "UPDATE_EXISTING_DELIVER_RESPONSE";
export const DELETE_DELIVER_RESPONSE = "DELETE_DELIVER_RESPONSE";

export const GET_INVENTORIES_RESPONSE = "GET_INVENTORYS_RESPONSE";
export const GET_INVENTORY_RESPONSE = "GET_INVENTORY_RESPONSE";
export const ADD_NEW_INVENTORY_RESPONSE = "ADD_NEW_INVENTORY_RESPONSE";
export const UPDATE_EXISTING_INVENTORY_RESPONSE =
  "UPDATE_EXISTING_INVENTORY_RESPONSE";
export const DELETE_INVENTORY_RESPONSE = "DELETE_INVENTORY_RESPONSE";

export const GET_ORDERS_RESPONSE = "GET_ORDERS_RESPONSE";
export const GET_ORDER_RESPONSE = "GET_ORDER_RESPONSE";
export const ADD_NEW_ORDER_RESPONSE = "ADD_NEW_ORDER_RESPONSE";
export const UPDATE_EXISTING_ORDER_RESPONSE = "UPDATE_EXISTING_ORDER_RESPONSE";
export const DELETE_ORDER_RESPONSE = "DELETE_ORDER_RESPONSE";

export const GET_ORDERLINES_RESPONSE = "GET_ORDERLINES_RESPONSE";
export const GET_ORDERLINE_RESPONSE = "GET_ORDERLINE_RESPONSE";
export const ADD_NEW_ORDERLINE_RESPONSE = "ADD_NEW_ORDERLINE_RESPONSE";
export const UPDATE_EXISTING_ORDERLINE_RESPONSE =
  "UPDATE_EXISTING_ORDERLINE_RESPONSE";
export const DELETE_ORDERLINE_RESPONSE = "DELETE_ORDERLINE_RESPONSE";

export const GET_PRODUCTCATEGORIES_RESPONSE = "GET_PRODUCTCATEGORIES_RESPONSE";
export const GET_PRODUCTCATEGORY_RESPONSE = "GET_PRODUCTCATEGORY_RESPONSE";
export const ADD_NEW_PRODUCTCATEGORY_RESPONSE =
  "ADD_NEW_PRODUCTCATEGORY_RESPONSE";
export const UPDATE_EXISTING_PRODUCTCATEGORY_RESPONSE =
  "UPDATE_EXISTING_PRODUCTCATEGORY_RESPONSE";
export const DELETE_PRODUCTCATEGORY_RESPONSE =
  "DELETE_PRODUCTCATEGORY_RESPONSE";

export const GET_PRODUCTIONS_RESPONSE = "GET_PRODUCTIONS_RESPONSE";
export const GET_PRODUCTION_RESPONSE = "GET_PRODUCTION_RESPONSE";
export const ADD_NEW_PRODUCTION_RESPONSE = "ADD_NEW_PRODUCTION_RESPONSE";
export const UPDATE_EXISTING_PRODUCTION_RESPONSE =
  "UPDATE_EXISTING_PRODUCTION_RESPONSE";
export const DELETE_PRODUCTION_RESPONSE = "DELETE_PRODUCTION_RESPONSE";

export const GET_ROUTINGS_RESPONSE = "GET_ROUTINGS_RESPONSE";
export const GET_ROUTING_RESPONSE = "GET_ROUTING_RESPONSE";
export const ADD_NEW_ROUTING_RESPONSE = "ADD_NEW_ROUTING_RESPONSE";
export const UPDATE_EXISTING_ROUTING_RESPONSE =
  "UPDATE_EXISTING_ROUTING_RESPONSE";
export const DELETE_ROUTING_RESPONSE = "DELETE_ROUTING_RESPONSE";

export const GET_ROUTINGWOKCENTERS_RESPONSE = "GET_ROUTINGWOKCENTERS_RESPONSE";
export const GET_ROUTINGWOKCENTER_RESPONSE = "GET_ROUTINGWOKCENTER_RESPONSE";
export const ADD_NEW_ROUTINGWOKCENTER_RESPONSE =
  "ADD_NEW_ROUTINGWOKCENTER_RESPONSE";
export const UPDATE_EXISTING_ROUTINGWOKCENTER_RESPONSE =
  "UPDATE_EXISTING_ROUTINGWOKCENTER_RESPONSE";
export const DELETE_ROUTINGWOKCENTER_RESPONSE =
  "DELETE_ROUTINGWOKCENTER_RESPONSE";

export const GET_UOMS_RESPONSE = "GET_UOMS_RESPONSE";
export const GET_UOM_RESPONSE = "GET_UOM_RESPONSE";
export const ADD_NEW_UOM_RESPONSE = "ADD_NEW_UOM_RESPONSE";
export const UPDATE_EXISTING_UOM_RESPONSE = "UPDATE_EXISTING_UOM_RESPONSE";
export const DELETE_UOM_RESPONSE = "DELETE_UOM_RESPONSE";

export const GET_CONTACTS_RESPONSE = "GET_CONTACTS_RESPONSE";
export const GET_CONTACT_RESPONSE = "GET_CONTACT_RESPONSE";
export const ADD_NEW_CONTACT_RESPONSE = "ADD_NEW_CONTACT_RESPONSE";
export const UPDATE_EXISTING_CONTACT_RESPONSE = "UPDATE_EXISTING_CONTACT_RESPONSE";
export const DELETE_CONTACT_RESPONSE = "DELETE_CONTACT_RESPONSE";

export const GET_ROUTINGWORKCENTERS_RESPONSE = "GET_ROUTINGWORKCENTERS_RESPONSE";
export const GET_ROUTINGWORKCENTER_RESPONSE = "GET_ROUTINGWORKCENTER_RESPONSE";
export const ADD_NEW_ROUTINGWORKCENTER_RESPONSE = "ADD_NEW_ROUTINGWORKCENTER_RESPONSE";
export const UPDATE_EXISTING_ROUTINGWORKCENTER_RESPONSE = "UPDATE_EXISTING_ROUTINGWORKCENTER_RESPONSE";
export const DELETE_ROUTINGWORKCENTER_RESPONSE = "DELETE_ROUTINGWORKCENTER_RESPONSE";

export const GET_USERS_RESPONSE = "GET_USERS_RESPONSE";
export const GET_USER_RESPONSE = "GET_USER_RESPONSE";
export const ADD_NEW_USER_RESPONSE = "ADD_NEW_USER_RESPONSE";
export const UPDATE_EXISTING_USER_RESPONSE = "UPDATE_EXISTING_USER_RESPONSE";
export const DELETE_USER_RESPONSE = "DELETE_USER_RESPONSE";

export const GET_WORKCENTERS_RESPONSE = "GET_WORKCENTERS_RESPONSE";
export const GET_WORKCENTER_RESPONSE = "GET_WORKCENTER_RESPONSE";
export const ADD_NEW_WORKCENTER_RESPONSE = "ADD_NEW_WORKCENTER_RESPONSE";
export const UPDATE_EXISTING_WORKCENTER_RESPONSE =
  "UPDATE_EXISTING_WORKCENTER_RESPONSE";
export const DELETE_WORKCENTER_RESPONSE = "DELETE_WORKCENTER_RESPONSE";

export const GET_WORKCENTERPRODUCTIVITIES_RESPONSE =
  "GET_WORKCENTERPRODUCTIVITIES_RESPONSE";
export const GET_WORKCENTERPRODUCTIVITY_RESPONSE =
  "GET_WORKCENTERPRODUCTIVITY_RESPONSE";
export const ADD_NEW_WORKCENTERPRODUCTIVITY_RESPONSE =
  "ADD_NEW_WORKCENTERPRODUCTIVITY_RESPONSE";
export const UPDATE_EXISTING_WORKCENTERPRODUCTIVITY_RESPONSE =
  "UPDATE_EXISTING_WORKCENTERPRODUCTIVITY_RESPONSE";
export const DELETE_WORKCENTERPRODUCTIVITY_RESPONSE =
  "DELETE_WORKCENTERPRODUCTIVITY_RESPONSE";

export const GET_WORKORDERS_RESPONSE = "GET_WORKORDERS_RESPONSE";
export const GET_WORKORDER_RESPONSE = "GET_WORKORDER_RESPONSE";
export const ADD_NEW_WORKORDER_RESPONSE = "ADD_NEW_WORKORDER_RESPONSE";
export const UPDATE_EXISTING_WORKORDER_RESPONSE =
  "UPDATE_EXISTING_WORKORDER_RESPONSE";
export const DELETE_WORKORDER_RESPONSE = "DELETE_WORKORDER_RESPONSE";

export const GET_PRODUCTS_RESPONSE = "GET_PRODUCTS_RESPONSE";
export const GET_PRODUCT_RESPONSE = "GET_PRODUCT_RESPONSE";
export const ADD_NEW_PRODUCT_RESPONSE = "ADD_NEW_PRODUCT_RESPONSE";
export const UPDATE_EXISTING_PRODUCT_RESPONSE =
  "UPDATE_EXISTING_PRODUCT_RESPONSE";
export const DELETE_PRODUCT_RESPONSE = "DELETE_PRODUCT_RESPONSE";

export const GET_COURSES_RESPONSE = "GET_COURSES_RESPONSE";
export const GET_COURSE_RESPONSE = "GET_COURSE_RESPONSE";
export const ADD_NEW_COURSE_RESPONSE = "ADD_NEW_COURSE_RESPONSE";
export const UPDATE_EXISTING_COURSE_RESPONSE =
  "UPDATE_EXISTING_COURSE_RESPONSE";
export const DELETE_COURSE_RESPONSE = "DELETE_COURSE_RESPONSE";

export const GET_AUTHORS_RESPONSE = "GET_AUTHORS_RESPONSE";

export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";
